models:
  - model: /models/Kunoichi-DPO-v2-7B
    parameters:
      weight: 0.4
  - model: /models/NeuralOmniWestBeaglake-7B
    parameters:
      weight: 0.6
base_model: /models/Mistral-7B-Instruct-v0.2
merge_method: task_arithmetic
dtype: bfloat16